services:
  api:
    build:
      context: ..
      dockerfile: desalter_optimization/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_PATH=/app/data/optimizer_anomalies.sqlite
    volumes:
      - db-data:/app/data
    restart: always
    container_name: desalter-api

  ui:
    build:
      context: ..
      dockerfile: desalter_optimization/Dockerfile.ui
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000/optimize
    depends_on:
      - api
    restart: always
    container_name: desalter-ui

volumes:
  db-data:

